export const defaultParams = {
    100: {
        Continue: {
            res: undefined,
            statusCode: 100,
            message: "Continue",
            data: null,
            error: null,
        },
        SwitchingProtocols: {
            res: undefined,
            statusCode: 101,
            message: "Switching Protocols",
            data: null,
            error: null,
        },
        Processing: {
            res: undefined,
            statusCode: 102,
            message: "Processing",
            data: null,
            error: null,
        },
    },

    200: {
        Ok: {
            res: undefined,
            statusCode: 200,
            message: "Ok",
            data: null,
            error: null,
        },
        Success: {
            res: undefined,
            statusCode: 200,
            message: "Success",
            data: null,
            error: null,
        },
        Created: {
            res: undefined,
            statusCode: 201,
            message: "Created",
            data: null,
            error: null,
        },
        Accepted: {
            res: undefined,
            statusCode: 202,
            message: "Accepted",
            data: null,
            error: null,
        },
        NonAuthoritativeInformation: {
            res: undefined,
            statusCode: 203,
            message: "Non-Authoritative Information",
            data: null,
            error: null,
        },
        NoContent: {
            res: undefined,
            statusCode: 204,
            message: "No Content",
            data: null,
            error: null,
        },
        ResetContent: {
            res: undefined,
            statusCode: 205,
            message: "Reset Content",
            data: null,
            error: null,
        },
        PartialContent: {
            res: undefined,
            statusCode: 206,
            message: "Partial Content",
            data: null,
            error: null,
        },
        MultiStatus: {
            res: undefined,
            statusCode: 207,
            message: "Multi-Status",
            data: null,
            error: null,
        },
        AlreadyReported: {
            res: undefined,
            statusCode: 208,
            message: "Already Reported",
            data: null,
            error: null,
        },
        IMUsed: {
            res: undefined,
            statusCode: 226,
            message: "Instance-Manipulations Used",
            data: null,
            error: null,
        },
    },

    300: {
        MultipleChoices: {
            res: undefined,
            statusCode: 300,
            message: "Multiple Choices",
            data: null,
            error: null,
        },
        MovedPermanently: {
            res: undefined,
            statusCode: 301,
            message: "Moved Permanently",
            data: null,
            error: null,
        },
        Found: {
            res: undefined,
            statusCode: 302,
            message: "Found",
            data: null,
            error: null,
        },
        SeeOther: {
            res: undefined,
            statusCode: 303,
            message: "See Other",
            data: null,
            error: null,
        },
        NotModified: {
            res: undefined,
            statusCode: 304,
            message: "Not Modified",
            data: null,
            error: null,
        },
        UseProxy: {
            res: undefined,
            statusCode: 305,
            message: "Use Proxy",
            data: null,
            error: null,
        },
        TemporaryRedirect: {
            res: undefined,
            statusCode: 307,
            message: "Temporary Redirect",
            data: null,
            error: null,
        },
        PermanentRedirect: {
            res: undefined,
            statusCode: 308,
            message: "Permanent Redirect",
            data: null,
            error: null,
        },
    },

    400: {
        BadRequest: {
            res: undefined,
            statusCode: 400,
            message: "Bad Request",
            data: null,
            error: null,
        },
        Unauthorized: {
            res: undefined,
            statusCode: 401,
            message: "Unauthorized",
            data: null,
            error: null,
        },
        Forbidden: {
            res: undefined,
            statusCode: 403,
            message: "Forbidden",
            data: null,
            error: null,
        },
        InvalidUrlError: {
            res: undefined,
            statusCode: 404,
            message: "Invalid URL",
            data: null,
            error: null,
        },
        NotFound: {
            res: undefined,
            statusCode: 404,
            message: "Not Found",
            data: null,
            error: null,
        },
        Conflict: {
            res: undefined,
            statusCode: 409,
            message: "Conflict",
            data: null,
            error: null,
        },
        UnprocessableEntity: {
            res: undefined,
            statusCode: 422,
            message: "Unprocessable Entity",
            data: null,
            error: null,
        },
        ValidationError: {
            res: undefined,
            statusCode: 422,
            message: "Validation Error",
            data: null,
            error: null,
        },
    },

    500: {
        InternalServerError: {
            res: undefined,
            statusCode: 500,
            message: "Internal Server Error",
            data: null,
            error: null,
        },
        NotImplemented: {
            res: undefined,
            statusCode: 501,
            message: "Not Implemented",
            data: null,
            error: null,
        },
        BadGateway: {
            res: undefined,
            statusCode: 502,
            message: "Bad Gateway",
            data: null,
            error: null,
        },
        ServiceUnavailable: {
            res: undefined,
            statusCode: 503,
            message: "Service Unavailable",
            data: null,
            error: null,
        },
        GatewayTimeout: {
            res: undefined,
            statusCode: 504,
            message: "Gateway Timeout",
            data: null,
            error: null,
        },
        HttpVersionNotSupported: {
            res: undefined,
            statusCode: 505,
            message: "Http Version Not Supported",
            data: null,
            error: null,
        },
        VariantAlsoNegotiates: {
            res: undefined,
            statusCode: 506,
            message: "Variant Also Negotiates",
            data: null,
            error: null,
        },
        InsufficientStorage: {
            res: undefined,
            statusCode: 507,
            message: "Insufficient Storage",
            data: null,
            error: null,
        },
        LoopDetected: {
            res: undefined,
            statusCode: 508,
            message: "Loop Detected",
            data: null,
            error: null,
        },
        BandwidthLimitExceeded: {
            res: undefined,
            statusCode: 509,
            message: "Bandwidth Limit Exceeded",
            data: null,
            error: null,
        },
        NotExtended: {
            res: undefined,
            statusCode: 510,
            message: "Not Extended",
            data: null,
            error: null,
        },
        NetworkAuthenticationRequired: {
            res: undefined,
            statusCode: 511,
            message: "Network Authentication Required",
            data: null,
            error: null,
        },
        NetworkReadTimeoutError: {
            res: undefined,
            statusCode: 598,
            message: "Network Read Timeout Error",
            data: null,
            error: null,
        },
        NetworkConnectTimeoutError: {
            res: undefined,
            statusCode: 599,
            message: "Network Connect Timeout Error",
            data: null,
            error: null,
        },
    },
};
